version: 2
jobs:
  build:
    working_directory: ~/circleci-vppsim
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: "Install virtual environment and requirements"
          command: make requirements
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "env"
      - run:
          name: "Lint sourcefiles and notebooks"
          command: make lint
